[package]
name = "env-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
i2cdev = "0.6"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
tokio = { version = "1.48", features = ["rt-multi-thread", "macros", "time"] }
futures = "0.3"
